/* =========================================================================
   Steward Trainer — données de contenu
   - COUNTRIES : pays / capitale / continent / code ISO2 / monnaie
     (le drapeau emoji est calculé à partir du code ISO → toujours correct)
   - AIRPORTS  : grands aéroports mondiaux (code IATA / ville / pays)
   - KNOWLEDGE : banque de questions métier (injectée depuis questions.js)
   ========================================================================= */
(function () {
  const COUNTRIES = [
    // ---- Europe ----
    ["France","Paris","Europe","FR","Euro"],
    ["Allemagne","Berlin","Europe","DE","Euro"],
    ["Espagne","Madrid","Europe","ES","Euro"],
    ["Italie","Rome","Europe","IT","Euro"],
    ["Portugal","Lisbonne","Europe","PT","Euro"],
    ["Royaume-Uni","Londres","Europe","GB","Livre sterling"],
    ["Irlande","Dublin","Europe","IE","Euro"],
    ["Belgique","Bruxelles","Europe","BE","Euro"],
    ["Pays-Bas","Amsterdam","Europe","NL","Euro"],
    ["Luxembourg","Luxembourg","Europe","LU","Euro"],
    ["Suisse","Berne","Europe","CH","Franc suisse"],
    ["Autriche","Vienne","Europe","AT","Euro"],
    ["Grèce","Athènes","Europe","GR","Euro"],
    ["Pologne","Varsovie","Europe","PL","Zloty"],
    ["Tchéquie","Prague","Europe","CZ","Couronne tchèque"],
    ["Slovaquie","Bratislava","Europe","SK","Euro"],
    ["Hongrie","Budapest","Europe","HU","Forint"],
    ["Suède","Stockholm","Europe","SE","Couronne suédoise"],
    ["Norvège","Oslo","Europe","NO","Couronne norvégienne"],
    ["Danemark","Copenhague","Europe","DK","Couronne danoise"],
    ["Finlande","Helsinki","Europe","FI","Euro"],
    ["Islande","Reykjavik","Europe","IS","Couronne islandaise"],
    ["Russie","Moscou","Europe","RU","Rouble"],
    ["Ukraine","Kiev","Europe","UA","Hryvnia"],
    ["Roumanie","Bucarest","Europe","RO","Leu"],
    ["Bulgarie","Sofia","Europe","BG","Lev"],
    ["Croatie","Zagreb","Europe","HR","Euro"],
    ["Serbie","Belgrade","Europe","RS","Dinar serbe"],
    ["Slovénie","Ljubljana","Europe","SI","Euro"],
    ["Bosnie-Herzégovine","Sarajevo","Europe","BA","Mark convertible"],
    ["Albanie","Tirana","Europe","AL","Lek"],
    ["Macédoine du Nord","Skopje","Europe","MK","Denar"],
    ["Estonie","Tallinn","Europe","EE","Euro"],
    ["Lettonie","Riga","Europe","LV","Euro"],
    ["Lituanie","Vilnius","Europe","LT","Euro"],
    ["Malte","La Valette","Europe","MT","Euro"],
    ["Chypre","Nicosie","Europe","CY","Euro"],
    // ---- Asie ----
    ["Chine","Pékin","Asie","CN","Yuan"],
    ["Japon","Tokyo","Asie","JP","Yen"],
    ["Corée du Sud","Séoul","Asie","KR","Won"],
    ["Corée du Nord","Pyongyang","Asie","KP","Won nord-coréen"],
    ["Inde","New Delhi","Asie","IN","Roupie indienne"],
    ["Pakistan","Islamabad","Asie","PK","Roupie pakistanaise"],
    ["Bangladesh","Dacca","Asie","BD","Taka"],
    ["Thaïlande","Bangkok","Asie","TH","Baht"],
    ["Vietnam","Hanoï","Asie","VN","Dong"],
    ["Cambodge","Phnom Penh","Asie","KH","Riel"],
    ["Laos","Vientiane","Asie","LA","Kip"],
    ["Myanmar","Naypyidaw","Asie","MM","Kyat"],
    ["Malaisie","Kuala Lumpur","Asie","MY","Ringgit"],
    ["Singapour","Singapour","Asie","SG","Dollar de Singapour"],
    ["Indonésie","Jakarta","Asie","ID","Roupie indonésienne"],
    ["Philippines","Manille","Asie","PH","Peso philippin"],
    ["Népal","Katmandou","Asie","NP","Roupie népalaise"],
    ["Kazakhstan","Astana","Asie","KZ","Tenge"],
    ["Ouzbékistan","Tachkent","Asie","UZ","Sum"],
    ["Afghanistan","Kaboul","Asie","AF","Afghani"],
    ["Iran","Téhéran","Asie","IR","Rial iranien"],
    ["Irak","Bagdad","Asie","IQ","Dinar irakien"],
    ["Arabie saoudite","Riyad","Asie","SA","Riyal saoudien"],
    ["Émirats arabes unis","Abou Dabi","Asie","AE","Dirham"],
    ["Qatar","Doha","Asie","QA","Riyal qatari"],
    ["Koweït","Koweït","Asie","KW","Dinar koweïtien"],
    ["Bahreïn","Manama","Asie","BH","Dinar bahreïni"],
    ["Oman","Mascate","Asie","OM","Rial omanais"],
    ["Yémen","Sanaa","Asie","YE","Rial yéménite"],
    ["Jordanie","Amman","Asie","JO","Dinar jordanien"],
    ["Liban","Beyrouth","Asie","LB","Livre libanaise"],
    ["Syrie","Damas","Asie","SY","Livre syrienne"],
    ["Israël","Jérusalem","Asie","IL","Shekel"],
    ["Turquie","Ankara","Asie","TR","Livre turque"],
    ["Géorgie","Tbilissi","Asie","GE","Lari"],
    ["Arménie","Erevan","Asie","AM","Dram"],
    ["Azerbaïdjan","Bakou","Asie","AZ","Manat azéri"],
    // ---- Afrique ----
    ["Égypte","Le Caire","Afrique","EG","Livre égyptienne"],
    ["Maroc","Rabat","Afrique","MA","Dirham marocain"],
    ["Algérie","Alger","Afrique","DZ","Dinar algérien"],
    ["Tunisie","Tunis","Afrique","TN","Dinar tunisien"],
    ["Libye","Tripoli","Afrique","LY","Dinar libyen"],
    ["Afrique du Sud","Pretoria","Afrique","ZA","Rand"],
    ["Nigeria","Abuja","Afrique","NG","Naira"],
    ["Kenya","Nairobi","Afrique","KE","Shilling kenyan"],
    ["Éthiopie","Addis-Abeba","Afrique","ET","Birr"],
    ["Ghana","Accra","Afrique","GH","Cedi"],
    ["Sénégal","Dakar","Afrique","SN","Franc CFA"],
    ["Côte d'Ivoire","Yamoussoukro","Afrique","CI","Franc CFA"],
    ["Mali","Bamako","Afrique","ML","Franc CFA"],
    ["Cameroun","Yaoundé","Afrique","CM","Franc CFA"],
    ["Tanzanie","Dodoma","Afrique","TZ","Shilling tanzanien"],
    ["Ouganda","Kampala","Afrique","UG","Shilling ougandais"],
    ["Angola","Luanda","Afrique","AO","Kwanza"],
    ["Mozambique","Maputo","Afrique","MZ","Metical"],
    ["Zimbabwe","Harare","Afrique","ZW","Dollar zimbabwéen"],
    ["Zambie","Lusaka","Afrique","ZM","Kwacha"],
    ["Botswana","Gaborone","Afrique","BW","Pula"],
    ["Namibie","Windhoek","Afrique","NA","Dollar namibien"],
    ["Madagascar","Antananarivo","Afrique","MG","Ariary"],
    ["Rwanda","Kigali","Afrique","RW","Franc rwandais"],
    ["République démocratique du Congo","Kinshasa","Afrique","CD","Franc congolais"],
    ["Congo","Brazzaville","Afrique","CG","Franc CFA"],
    ["Gabon","Libreville","Afrique","GA","Franc CFA"],
    ["Soudan","Khartoum","Afrique","SD","Livre soudanaise"],
    ["Tchad","N'Djamena","Afrique","TD","Franc CFA"],
    ["Niger","Niamey","Afrique","NE","Franc CFA"],
    ["Burkina Faso","Ouagadougou","Afrique","BF","Franc CFA"],
    ["Guinée","Conakry","Afrique","GN","Franc guinéen"],
    ["Bénin","Porto-Novo","Afrique","BJ","Franc CFA"],
    ["Togo","Lomé","Afrique","TG","Franc CFA"],
    ["Mauritanie","Nouakchott","Afrique","MR","Ouguiya"],
    ["Maurice","Port-Louis","Afrique","MU","Roupie mauricienne"],
    // ---- Amérique du Nord ----
    ["États-Unis","Washington","Amérique du Nord","US","Dollar américain"],
    ["Canada","Ottawa","Amérique du Nord","CA","Dollar canadien"],
    ["Mexique","Mexico","Amérique du Nord","MX","Peso mexicain"],
    ["Cuba","La Havane","Amérique du Nord","CU","Peso cubain"],
    ["Guatemala","Guatemala","Amérique du Nord","GT","Quetzal"],
    ["Honduras","Tegucigalpa","Amérique du Nord","HN","Lempira"],
    ["Panama","Panama","Amérique du Nord","PA","Balboa"],
    ["Costa Rica","San José","Amérique du Nord","CR","Colón"],
    ["Jamaïque","Kingston","Amérique du Nord","JM","Dollar jamaïcain"],
    ["République dominicaine","Saint-Domingue","Amérique du Nord","DO","Peso dominicain"],
    ["Haïti","Port-au-Prince","Amérique du Nord","HT","Gourde"],
    ["Salvador","San Salvador","Amérique du Nord","SV","Dollar américain"],
    ["Nicaragua","Managua","Amérique du Nord","NI","Córdoba"],
    // ---- Amérique du Sud ----
    ["Brésil","Brasilia","Amérique du Sud","BR","Réal"],
    ["Argentine","Buenos Aires","Amérique du Sud","AR","Peso argentin"],
    ["Chili","Santiago","Amérique du Sud","CL","Peso chilien"],
    ["Pérou","Lima","Amérique du Sud","PE","Sol"],
    ["Colombie","Bogota","Amérique du Sud","CO","Peso colombien"],
    ["Venezuela","Caracas","Amérique du Sud","VE","Bolívar"],
    ["Équateur","Quito","Amérique du Sud","EC","Dollar américain"],
    ["Bolivie","La Paz","Amérique du Sud","BO","Boliviano"],
    ["Paraguay","Asuncion","Amérique du Sud","PY","Guarani"],
    ["Uruguay","Montevideo","Amérique du Sud","UY","Peso uruguayen"],
    // ---- Océanie ----
    ["Australie","Canberra","Océanie","AU","Dollar australien"],
    ["Nouvelle-Zélande","Wellington","Océanie","NZ","Dollar néo-zélandais"],
    ["Fidji","Suva","Océanie","FJ","Dollar fidjien"],
    ["Papouasie-Nouvelle-Guinée","Port Moresby","Océanie","PG","Kina"],
  ].map(r => ({ n:r[0], cap:r[1], c:r[2], iso:r[3], cur:r[4] }));

  const AIRPORTS = [
    ["CDG","Paris","France"],["ORY","Paris","France"],["NCE","Nice","France"],
    ["LYS","Lyon","France"],["MRS","Marseille","France"],["TLS","Toulouse","France"],
    ["BOD","Bordeaux","France"],["NTE","Nantes","France"],
    ["LHR","Londres","Royaume-Uni"],["LGW","Londres","Royaume-Uni"],["MAN","Manchester","Royaume-Uni"],["EDI","Édimbourg","Royaume-Uni"],
    ["JFK","New York","États-Unis"],["EWR","Newark","États-Unis"],["LGA","New York","États-Unis"],
    ["LAX","Los Angeles","États-Unis"],["SFO","San Francisco","États-Unis"],["ORD","Chicago","États-Unis"],
    ["MIA","Miami","États-Unis"],["ATL","Atlanta","États-Unis"],["DFW","Dallas","États-Unis"],
    ["SEA","Seattle","États-Unis"],["BOS","Boston","États-Unis"],["IAD","Washington","États-Unis"],
    ["DEN","Denver","États-Unis"],["LAS","Las Vegas","États-Unis"],["MCO","Orlando","États-Unis"],
    ["PHX","Phoenix","États-Unis"],["IAH","Houston","États-Unis"],
    ["HND","Tokyo","Japon"],["NRT","Tokyo","Japon"],["KIX","Osaka","Japon"],
    ["PEK","Pékin","Chine"],["PVG","Shanghai","Chine"],["CAN","Canton","Chine"],["HKG","Hong Kong","Chine"],
    ["ICN","Séoul","Corée du Sud"],["TPE","Taipei","Taïwan"],
    ["SIN","Singapour","Singapour"],["BKK","Bangkok","Thaïlande"],["KUL","Kuala Lumpur","Malaisie"],
    ["CGK","Jakarta","Indonésie"],["MNL","Manille","Philippines"],
    ["SGN","Hô Chi Minh-Ville","Vietnam"],["HAN","Hanoï","Vietnam"],
    ["DEL","New Delhi","Inde"],["BOM","Mumbai","Inde"],["KHI","Karachi","Pakistan"],["DAC","Dacca","Bangladesh"],
    ["KTM","Katmandou","Népal"],["CMB","Colombo","Sri Lanka"],["MLE","Malé","Maldives"],
    ["DXB","Dubaï","Émirats arabes unis"],["AUH","Abou Dabi","Émirats arabes unis"],["DOH","Doha","Qatar"],
    ["JED","Djeddah","Arabie saoudite"],["RUH","Riyad","Arabie saoudite"],
    ["IST","Istanbul","Turquie"],["TLV","Tel Aviv","Israël"],
    ["CAI","Le Caire","Égypte"],["JNB","Johannesburg","Afrique du Sud"],["CPT","Le Cap","Afrique du Sud"],
    ["NBO","Nairobi","Kenya"],["ADD","Addis-Abeba","Éthiopie"],["LOS","Lagos","Nigeria"],
    ["CMN","Casablanca","Maroc"],["ALG","Alger","Algérie"],["TUN","Tunis","Tunisie"],["DKR","Dakar","Sénégal"],
    ["FRA","Francfort","Allemagne"],["MUC","Munich","Allemagne"],["BER","Berlin","Allemagne"],["DUS","Düsseldorf","Allemagne"],
    ["AMS","Amsterdam","Pays-Bas"],["MAD","Madrid","Espagne"],["BCN","Barcelone","Espagne"],
    ["FCO","Rome","Italie"],["MXP","Milan","Italie"],["LIS","Lisbonne","Portugal"],["BRU","Bruxelles","Belgique"],
    ["ZRH","Zurich","Suisse"],["GVA","Genève","Suisse"],["VIE","Vienne","Autriche"],
    ["CPH","Copenhague","Danemark"],["ARN","Stockholm","Suède"],["OSL","Oslo","Norvège"],["HEL","Helsinki","Finlande"],
    ["DUB","Dublin","Irlande"],["ATH","Athènes","Grèce"],["WAW","Varsovie","Pologne"],["PRG","Prague","Tchéquie"],
    ["BUD","Budapest","Hongrie"],["OTP","Bucarest","Roumanie"],["SVO","Moscou","Russie"],["LED","Saint-Pétersbourg","Russie"],
    ["KEF","Reykjavik","Islande"],
    ["YYZ","Toronto","Canada"],["YVR","Vancouver","Canada"],["YUL","Montréal","Canada"],
    ["MEX","Mexico","Mexique"],["CUN","Cancún","Mexique"],
    ["GRU","São Paulo","Brésil"],["GIG","Rio de Janeiro","Brésil"],["EZE","Buenos Aires","Argentine"],
    ["SCL","Santiago","Chili"],["LIM","Lima","Pérou"],["BOG","Bogota","Colombie"],
    ["SYD","Sydney","Australie"],["MEL","Melbourne","Australie"],["BNE","Brisbane","Australie"],["PER","Perth","Australie"],
    ["AKL","Auckland","Nouvelle-Zélande"],
  ].map(r => ({ code:r[0], city:r[1], country:r[2] }));

  window.STEWARD_DATA = window.STEWARD_DATA || {};
  window.STEWARD_DATA.COUNTRIES = COUNTRIES;
  window.STEWARD_DATA.AIRPORTS = AIRPORTS;
  window.STEWARD_DATA.KNOWLEDGE = window.STEWARD_DATA.KNOWLEDGE || {};
})();
